#!/usr/bin/env bash

# Name: kurzit
# Brief: An super-efficient, expandable, fast BASH shell environment customizer.
# Brief: The setup script for Kurzit. This will make small modifications to your profile, so that Kurzit will run at init.
# Author: Mike Pruett <mikepruett3@gmail.com>

# Setup Variables
BashVer=$(bash --version | head -n 1 | awk '{ print $4 }')
Kern=$(uname -s)
KernVer=$(uname -r)
ScriptName=$(basename $0)
TEST=$(pwd)
echo $TEST

function Set_KurzitHome () {
    # 1st Check for empty variable
    if [ -z $kurzit_home ]; then
        # Check if $HOME/.kurzit exists, then use it for kurzit_home
        if [ -d $HOME/.kurzit/ ]; then
            if [ -e $HOME/.kurzit/kurzit ]; then
                export kurzit_home=$HOME/.kurzit
            fi
        fi

         # Check if $HOME/kurzit exists, then use it for kurzit_home
        if [ -d $HOME/kurzit/ ]; then
            if [ -e $HOME/kurzit/kurzit ]; then
                export kurzit_home=$HOME/kurzit
            fi
        fi
    fi

    # 2nd Check for empty variable
    if [ -z $kurzit_home ]; then
        echo -n "Cannot find the kurzit_home variable..."
        echo -n "Please type in the path:"
        read kurzit_home
        export kurzit_home
            if ! [ -d $kurzit_home ]; then
                echo Cannot find the kurzit_home variable, exiting script
                exit 1
            fi
    fi
}

function Link_Kurzitrc () {
    if [ ! -e ~/.kurzitrc ]; then
        ln -s $kurzit_home/kurzitrc ~/.kurzitrc
    fi
}

# Set the $kurzit_home variable
Set_KurzitHome

# Import Functions
for fn in $(find $kurzit_home/functions/ -type f ); do
    source $fn
done

# Call Functions
Get_Distro

#Link_Kurzitrc

# Searching for .bashrc, and exit if not found!
if [ ! -e ~/.bashrc ]; then
    echo -n "Cannot find .bashrc, exiting!"
    exit 1
fi

# Modifying .bashrc with variables needed to run kurzit
if [[ $(grep -c "DIST" ~/.bashrc) -eq 0 ]]; then
    echo "" >> ~/.bashrc
    echo "# Kurzit Variables:" >> ~/.bashrc
    echo export DIST="$DISTRO" >> ~/.bashrc
fi

if [[ $(grep -c "kurzit_home" ~/.bashrc) -eq 0 ]]; then
    echo export kurzit_home=$kurzit_home >> ~/.bashrc
fi

if [[ $(grep -c "kurzitrc" ~/.bashrc) -eq 0 ]]; then
    echo source $kurzit_home/kurzitrc >> ~/.bashrc
fi

# Check if Starship Cross-Platform Prompt is installed
hash starship &> /dev/null
if [ $? -eq 0 ]; then
    echo "" >> ~/.bashrc
    echo "# Starship Variables:" >> ~/.bashrc
    echo export STARSHIP_DISTRO="$ICON " >> ~/.bashrc
    echo export STARSHIP_CONFIG=~/.config/starship.toml >> ~/.bashrc
    echo 'eval "$(starship init bash)"' >> ~/.bashrc
fi
