#!/usr/bin/env bash

# Load Appropriate Alias Scripts based on $DIST
function Load_Aliases () {
    if [ $DIST -eq "MacOS" ]; then
        # Distro Specific
        for fn in $(find $kurzit_home/aliases/ -name "*.$DIST"); do
            . $fn
        done
    else
        # General Bash Aliases
        for fn in $(find $kurzit_home/aliases/ -name "*.Bash"); do
            . $fn
        done
    fi
}

# Load Utilities
function Load_Utilities () {
    # General Bash Aliases
    for fn in $(find $kurzit_home/utils/ -type f ); do
        . $fn
    done
}

# Unalias existing Aliases
function Alias_Check () {
    _alias=$1
    if [[ $(type -t $_alias) == "alias" ]]; then
        unalias $_alias
    fi
}

# Parse Date of Last Update
function Last_Update_Check () {
    _kurzit_last_update=$(cat ~/.kdup)
    if [ -z $_kurzit_last_update ]; then
        echo "Cannot find Last Update, running update script..."
        $kurzit_home/update
    else
        if [ $(( ( $(date +%s) - _kurzit_last_update )/(60*60*24) )) -ge "14" ]; then
            echo "Checking for Latest Kurzit Update, running update script..."
            $kurzit_home/update
        fi
    fi
}

# Main Script
Last_Update_Check
Load_Aliases
Load_Utilities
