#!/usr/bin/env bash

# Load Appropriate Alias Scripts based on $DIST
function Load_Aliases () {
    # General Bash Aliases
    for fn in $(find $kurzit_home/aliases/ -name "*.Bash"); do
        . $fn
    done

    # Distro Specific
    for fn in $(find $kurzit_home/aliases/ -name "*.$DIST"); do
        . $fn
    done
}

# Load Utilities
function Load_Utilities () {
    # General Bash Aliases
    for fn in $(find $kurzit_home/utils/ -type f ); do
        . $fn
    done
}

# Unalias existing Aliases
function Alias_Check () {
    _alias=$1
    if [[ $(type -t $_alias) == "alias" ]]; then
        unalias $_alias
    fi
}

Load_Aliases
Load_Utilities