#!/usr/bin/env bash

# Load Appropriate Alias Scripts based on $DIST
function Load_Aliases () {
    # General Bash Aliases
    for fn in $(find $kurzit_home/aliases/ -name "*.Bash"); do
        . $fn
    done

    # Distro Specific
    for fn in $(find $kurzit_home/aliases/ -name "*.$DIST"); do
        . $fn
    done
}

# Load Utilities
function Load_Utilities () {
    # General Bash Aliases
    for fn in $(find $kurzit_home/utils/ -type f ); do
        . $fn
    done
}

# Unalias existing Aliases
function Alias_Check () {
    _alias=$1
    if [[ $(type -t $_alias) == "alias" ]]; then
        unalias $_alias
    fi
}

# Parse Date of Last Update
function Last_Update_Check () {
    if [ -z $_kurzit_update ]; then
        echo -n "Cannot find Last Update, running update script..."
        $kurzit_home/utils/update
    else
         _now=$(date +"%Y%m%d")
         if [ $(expr $now - $_kurzit_update) -ge 14 ]; then
            echo -n "Checking for Latest Kurzit Update, running update script..."
            $kurzit_home/utils/update
         fi
    fi
}

# Main Script
Last_Update_Check
Load_Aliases
Load_Utilities