#!/usr/bin/env bash

# Name: kurzit
# Brief: An super-efficient, expandable, fast BASH shell environment customizer.
# Brief: The setup script for Kurzit. This will make small modifications to your profile, so that Kurzit will run at init.
# Author: Mike Pruett <mikepruett3@gmail.com>

# Setup Variables
BashVer=$(bash --version | head -n 1 | awk '{ print $4 }')
Kern=$(uname -s)
KernVer=$(uname -r)
ScriptName=${FUNCNAME[0]}

# Set the $kurzit_home variable
if [ -z $kurzit_home ]; then
    echo -n "Cannot find the kurzit_home variable..."
    echo -n "Please type in the path:"
    read kurzit_home
    export kurzit_home
        if ! [ -d $kurzit_home ]; then
            echo Cannot find the kurzit_home variable, exiting script
            exit 1
        fi
else
    # Check if $HOME/.kurzit exists, then use it for kurzit_home
    KURZIT_DIRS=(".kurzit" "kurzit")
    for DIR in $KURZIT_DIRS; do
        if [ -d $HOME/$DIR/ ]; then
            if [ -e $HOME/$DIR/kurzit ]; then
                export kurzit_home=$HOME/$DIR
            fi
        fi
    done
fi

# Import Functions
for fn in $(find $kurzit_home/functions/ -type f ); do
    source $fn
done

# Call Functions
Get_Distro

# Searching for .bashrc, and exit if not found!
if [ ! -e ~/.bashrc ]; then
    echo -n "Cannot find .bashrc, exiting!"
    exit 1
fi

# Modifying .bashrc with variables needed to run kurzit
if [[ $(grep -c "DIST" ~/.bashrc) -eq 0 ]]; then
    echo "" >> ~/.bashrc
    echo "# Kurzit Variables:" >> ~/.bashrc
    echo export DIST="$DISTRO" >> ~/.bashrc
fi

if [[ $(grep -c "kurzit_home" ~/.bashrc) -eq 0 ]]; then
    echo export kurzit_home=$kurzit_home >> ~/.bashrc
fi

if [[ $(grep -c "kurzitrc" ~/.bashrc) -eq 0 ]]; then
    echo source $kurzit_home/kurzitrc >> ~/.bashrc
fi

# Check if Starship Cross-Platform Prompt is installed
hash starship &> /dev/null
if [ $? -eq 0 ]; then
    if [[ $(grep -c "STARSHIP_DISTRO" ~/.bashrc) -eq 0 ]]; then
        echo "" >> ~/.bashrc
        echo "# Starship Variables:" >> ~/.bashrc
        echo export STARSHIP_DISTRO="$ICON " >> ~/.bashrc
        echo export STARSHIP_CONFIG=~/.config/starship.toml >> ~/.bashrc
        echo 'eval "$(starship init bash)"' >> ~/.bashrc
    fi
fi
